// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWlEPz1LaCT75hdgdYGxpE7Q2YeLg2NWM',
    appId: '1:581505991376:web:9504159843d75fd55714d5',
    messagingSenderId: '581505991376',
    projectId: 'brandnextdoor',
    authDomain: 'brandnextdoor.firebaseapp.com',
    storageBucket: 'brandnextdoor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZbpvQeCDmhewRsOYTzBDrRet7WSDguc',
    appId: '1:581505991376:android:6b9ac19c4c9c3fa45714d5',
    messagingSenderId: '581505991376',
    projectId: 'brandnextdoor',
    storageBucket: 'brandnextdoor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATkvKOcSPYqik9gUaT6o23LXdXeRwKb1U',
    appId: '1:581505991376:ios:7b50b1809ab27c4b5714d5',
    messagingSenderId: '581505991376',
    projectId: 'brandnextdoor',
    storageBucket: 'brandnextdoor.firebasestorage.app',
    iosBundleId: 'com.example.brandNextDoor',
  );

}